def raise_exception():
    
     num = "not_a_number" + 3